
# hybrid_dataloader.py
"""
Hybrid dataloader with ONLINE trajectory generation from the student model.
Trajectories are regenerated every K steps using the current model.
"""

import json
import random
import threading
from collections import deque
import numpy as np
import torch
from torch.utils.data import Dataset, IterableDataset, DataLoader
from datasets import load_from_disk, load_dataset
from transformers import AutoTokenizer


class UniRef50Dataset(Dataset):
    def __init__(self, cache_dir, split='train', max_len=128, tokenizer=None):
        self.max_len = max_len
        if tokenizer is None:
            self.tokenizer = AutoTokenizer.from_pretrained('facebook/esm2_t33_650M_UR50D')
        else:
            print('tokenizer is None')
        self.dataset = load_from_disk(f"{cache_dir}/uniref50")
        if split == 'train':
            self.dataset = self.dataset['train']
        else:
            self.dataset = self.dataset.get('test', self.dataset.get('validation', self.dataset['train']))
    def __len__(self):
        return len(self.dataset)
    def __getitem__(self, idx):
        seq = self.dataset[idx]['sequence'][:self.max_len - 2]
        encoded = self.tokenizer(seq, max_length=self.max_len, padding='max_length', 
                                  truncation=True, return_tensors='pt')
        return {
            'input_ids': encoded['input_ids'].squeeze(0),
            'attention_mask': encoded['attention_mask'].squeeze(0),
            'unmask_order': None,
            'is_trajectory': False
        }
class OnlineTrajectoryBuffer:
    """
    Thread-safe buffer that stores trajectories generated by the student model.
    Trajectories are refreshed every `refresh_interval` steps.
    """
    def __init__(self, max_size=10000, refresh_interval=100):
        self.buffer = deque(maxlen=max_size)
        self.refresh_interval = refresh_interval
        self.last_refresh_step = -refresh_interval  # Force refresh on first call
        self.lock = threading.Lock()
        self._pending_samples = []
    def should_refresh(self, current_step):
        """Check if we should generate new trajectories."""
        return current_step - self.last_refresh_step >= self.refresh_interval
    def add_trajectories(self, trajectories, current_step):
        with self.lock:
            self.buffer.extend(trajectories)
            self.last_refresh_step = current_step
            print(f"[trajectory] Added {len(trajectories)} samples at step {current_step}, "
                  f"buffer size: {len(self.buffer)}")
    def sample(self):
        with self.lock:
            if len(self.buffer) == 0:
                return None
            idx = random.randint(0, len(self.buffer) - 1)
            return self.buffer[idx]
    def __len__(self):
        with self.lock:
            return len(self.buffer)

class HybridCurriculumDataset(IterableDataset):
    """
    Streams samples mixing UniRef50 and ONLINE-GENERATED trajectories.
    
    Key difference from static version:
    - Trajectories come from `trajectory_buffer` which is updated by the model
    - No pre-loaded trajectory file needed
    """
    
    def __init__(
        self,
        uniref_dataset: Dataset,
        trajectory_buffer: OnlineTrajectoryBuffer,
        warmup_steps: int = 2000,
        alpha_increase_interval: int = 100,
        alpha_increment: float = 0.05,
        max_alpha: float = 0.8,
        seed: int = 42
    ):
        self.uniref = uniref_dataset
        self.traj_buffer = trajectory_buffer
        self.warmup_steps = warmup_steps
        self.alpha_increase_interval = alpha_increase_interval
        self.alpha_increment = alpha_increment
        self.max_alpha = max_alpha
        self.seed = seed
        self._current_step = 0
        self._rng = random.Random(seed)
    def set_step(self, step: int):
        self._current_step = step
    def get_alpha(self) -> float:
        if self._current_step < self.warmup_steps:
            return 0.0
        steps_since_warmup = self._current_step - self.warmup_steps
        num_increases = steps_since_warmup // self.alpha_increase_interval + 1
        return min(self.max_alpha, num_increases * self.alpha_increment)
    def __iter__(self):
        worker_info = torch.utils.data.get_worker_info()
        if worker_info is not None:
            self._rng = random.Random(self.seed + worker_info.id)
        while True:
            alpha = self.get_alpha()
            # Try to sample from trajectory buffer if alpha > 0 and buffer has samples
            if self._rng.random() < alpha and len(self.traj_buffer) > 0:
                traj = self.traj_buffer.sample()
                if traj is not None:
                    yield traj
                    continue
            # Otherwise sample from UniRef50
            idx = self._rng.randint(0, len(self.uniref) - 1)
            yield self.uniref[idx]

def collate_hybrid(batch):
    max_len = max(x['input_ids'].size(0) for x in batch)
    B = len(batch)
    input_ids = torch.zeros(B, max_len, dtype=torch.long)
    attention_mask = torch.zeros_like(input_ids, dtype = torch.long)
    unmask_orders = []
    is_trajectory = []

    for i, x in enumerate(batch):
        ids = x['input_ids']
        L = ids.shape[0]
        input_ids[i, :L] = ids
        mask = x.get('attention_mask', None)
        if mask is not None:
            if not torch.is_tensor(mask):
                mask = torch.tensor(mask, dtype=torch.long)
            attention_mask[i, :mask.shape[0]] = mask
        else:
            attention_mask[i, :L] = 1

        unmask_orders.append(x.get('unmask_order', None))
        is_trajectory.append(x.get('is_trajectory', False))
        return {
        'input_ids': input_ids,
        'attention_mask': attention_mask,
        'unmask_order': unmask_orders,
        'unmask_order_flat': [None] * B,
        'is_trajectory': torch.tensor(is_trajectory, dtype=torch.bool)
        }
    
def convert_generated_sample_to_trajectory(sample, max_len=128):
    """
    Convert a sample from model.generated_samples to trajectory format.
    
    The model's _sample() stores:
    - x0_tokens: final generated sequence
    - unmasked_indices: list of lists, indices revealed at each step
    - unmasked_tokens: list of lists, tokens revealed at each step
    
    We convert to training format with REVERSED order for easy→hard curriculum.
    """
    tokens = sample['x0_tokens'][:max_len]
    unmasked_indices = sample['unmasked_indices']
    
    # Filter indices that exceed max_len
    truncated_order = []
    for step_indices in unmasked_indices:
        valid = [i for i in step_indices if i < len(tokens)]
        truncated_order.append(valid)
    
    return {
        'input_ids': torch.tensor(tokens, dtype=torch.long),
        'attention_mask': torch.ones(len(tokens), dtype=torch.long),
        'unmask_order': truncated_order,  # Already in denoising order (easy first)
        'is_trajectory': True
    }